services:
  claude-agent:
    build: .
    ports:
      - "${PORT:-9999}:${PORT:-9999}"
    volumes:
      - claude-workspace:/workspace
    env_file:
      - .env
    restart: unless-stopped

volumes:
  claude-workspace:
