services:
  claude-agent:
    build: .
    ports:
      # publish a random host port -> container 9999
      - target: 9999
        published: 0
        protocol: tcp
    volumes:
      - claude-workspace:/workspace
    env_file:
      - .env
    restart: unless-stopped

volumes:
  claude-workspace:
